#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova.logica.bdd
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Innova")]
	public partial class InnovaDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCOMENTARIO(COMENTARIO instance);
    partial void UpdateCOMENTARIO(COMENTARIO instance);
    partial void DeleteCOMENTARIO(COMENTARIO instance);
    partial void InsertVALORACIONE(VALORACIONE instance);
    partial void UpdateVALORACIONE(VALORACIONE instance);
    partial void DeleteVALORACIONE(VALORACIONE instance);
    partial void InsertEMPRESA(EMPRESA instance);
    partial void UpdateEMPRESA(EMPRESA instance);
    partial void DeleteEMPRESA(EMPRESA instance);
    partial void InsertEXP_EDUCACIONALE(EXP_EDUCACIONALE instance);
    partial void UpdateEXP_EDUCACIONALE(EXP_EDUCACIONALE instance);
    partial void DeleteEXP_EDUCACIONALE(EXP_EDUCACIONALE instance);
    partial void InsertEXP_EMPRENDEDORE(EXP_EMPRENDEDORE instance);
    partial void UpdateEXP_EMPRENDEDORE(EXP_EMPRENDEDORE instance);
    partial void DeleteEXP_EMPRENDEDORE(EXP_EMPRENDEDORE instance);
    partial void InsertEXP_LABORALE(EXP_LABORALE instance);
    partial void UpdateEXP_LABORALE(EXP_LABORALE instance);
    partial void DeleteEXP_LABORALE(EXP_LABORALE instance);
    partial void InsertHABILIDADE(HABILIDADE instance);
    partial void UpdateHABILIDADE(HABILIDADE instance);
    partial void DeleteHABILIDADE(HABILIDADE instance);
    partial void InsertINSTITUCIONE(INSTITUCIONE instance);
    partial void UpdateINSTITUCIONE(INSTITUCIONE instance);
    partial void DeleteINSTITUCIONE(INSTITUCIONE instance);
    partial void InsertLOG_ERRORE(LOG_ERRORE instance);
    partial void UpdateLOG_ERRORE(LOG_ERRORE instance);
    partial void DeleteLOG_ERRORE(LOG_ERRORE instance);
    partial void InsertNIVEL_ERRORE(NIVEL_ERRORE instance);
    partial void UpdateNIVEL_ERRORE(NIVEL_ERRORE instance);
    partial void DeleteNIVEL_ERRORE(NIVEL_ERRORE instance);
    partial void InsertPROFESIONE(PROFESIONE instance);
    partial void UpdatePROFESIONE(PROFESIONE instance);
    partial void DeletePROFESIONE(PROFESIONE instance);
    partial void InsertPROYECTO(PROYECTO instance);
    partial void UpdatePROYECTO(PROYECTO instance);
    partial void DeletePROYECTO(PROYECTO instance);
    partial void InsertROLE(ROLE instance);
    partial void UpdateROLE(ROLE instance);
    partial void DeleteROLE(ROLE instance);
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    #endregion
		
		public InnovaDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["InnovaConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InnovaDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InnovaDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InnovaDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InnovaDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COMENTARIO> COMENTARIOs
		{
			get
			{
				return this.GetTable<COMENTARIO>();
			}
		}
		
		public System.Data.Linq.Table<VALORACIONE> VALORACIONEs
		{
			get
			{
				return this.GetTable<VALORACIONE>();
			}
		}
		
		public System.Data.Linq.Table<EMPRESA> EMPRESAs
		{
			get
			{
				return this.GetTable<EMPRESA>();
			}
		}
		
		public System.Data.Linq.Table<EXP_EDUCACIONALE> EXP_EDUCACIONALEs
		{
			get
			{
				return this.GetTable<EXP_EDUCACIONALE>();
			}
		}
		
		public System.Data.Linq.Table<EXP_EMPRENDEDORE> EXP_EMPRENDEDOREs
		{
			get
			{
				return this.GetTable<EXP_EMPRENDEDORE>();
			}
		}
		
		public System.Data.Linq.Table<EXP_LABORALE> EXP_LABORALEs
		{
			get
			{
				return this.GetTable<EXP_LABORALE>();
			}
		}
		
		public System.Data.Linq.Table<HABILIDADE> HABILIDADEs
		{
			get
			{
				return this.GetTable<HABILIDADE>();
			}
		}
		
		public System.Data.Linq.Table<HABILIDADES_USUARIO> HABILIDADES_USUARIOs
		{
			get
			{
				return this.GetTable<HABILIDADES_USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<INSTITUCIONE> INSTITUCIONEs
		{
			get
			{
				return this.GetTable<INSTITUCIONE>();
			}
		}
		
		public System.Data.Linq.Table<LOG_ERRORE> LOG_ERROREs
		{
			get
			{
				return this.GetTable<LOG_ERRORE>();
			}
		}
		
		public System.Data.Linq.Table<NIVEL_ERRORE> NIVEL_ERROREs
		{
			get
			{
				return this.GetTable<NIVEL_ERRORE>();
			}
		}
		
		public System.Data.Linq.Table<PROFESIONE> PROFESIONEs
		{
			get
			{
				return this.GetTable<PROFESIONE>();
			}
		}
		
		public System.Data.Linq.Table<PROYECTO> PROYECTOs
		{
			get
			{
				return this.GetTable<PROYECTO>();
			}
		}
		
		public System.Data.Linq.Table<ROLE> ROLEs
		{
			get
			{
				return this.GetTable<ROLE>();
			}
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIOs
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<MENSAJE> MENSAJEs
		{
			get
			{
				return this.GetTable<MENSAJE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMENTARIOS")]
	public partial class COMENTARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_COMENTARIO;
		
		private System.Nullable<int> _ID_USUARIO_EMISOR;
		
		private System.Nullable<int> _ID_USUARIO_RECEPTOR;
		
		private string _COMENTARIO_CORTA;
		
		private string _COMENTARIO_LARGO;
		
		private System.Nullable<int> _ID_VALORACION;
		
		private System.Nullable<System.DateTime> _FECHA_INGRESO;
		
		private EntityRef<VALORACIONE> _VALORACIONE;
		
		private EntityRef<USUARIO> _USUARIO;
		
		private EntityRef<USUARIO> _USUARIO1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_COMENTARIOChanging(int value);
    partial void OnID_COMENTARIOChanged();
    partial void OnID_USUARIO_EMISORChanging(System.Nullable<int> value);
    partial void OnID_USUARIO_EMISORChanged();
    partial void OnID_USUARIO_RECEPTORChanging(System.Nullable<int> value);
    partial void OnID_USUARIO_RECEPTORChanged();
    partial void OnCOMENTARIO_CORTAChanging(string value);
    partial void OnCOMENTARIO_CORTAChanged();
    partial void OnCOMENTARIO_LARGOChanging(string value);
    partial void OnCOMENTARIO_LARGOChanged();
    partial void OnID_VALORACIONChanging(System.Nullable<int> value);
    partial void OnID_VALORACIONChanged();
    partial void OnFECHA_INGRESOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_INGRESOChanged();
    #endregion
		
		public COMENTARIO()
		{
			this._VALORACIONE = default(EntityRef<VALORACIONE>);
			this._USUARIO = default(EntityRef<USUARIO>);
			this._USUARIO1 = default(EntityRef<USUARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_COMENTARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_COMENTARIO
		{
			get
			{
				return this._ID_COMENTARIO;
			}
			set
			{
				if ((this._ID_COMENTARIO != value))
				{
					this.OnID_COMENTARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_COMENTARIO = value;
					this.SendPropertyChanged("ID_COMENTARIO");
					this.OnID_COMENTARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO_EMISOR", DbType="Int")]
		public System.Nullable<int> ID_USUARIO_EMISOR
		{
			get
			{
				return this._ID_USUARIO_EMISOR;
			}
			set
			{
				if ((this._ID_USUARIO_EMISOR != value))
				{
					if (this._USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USUARIO_EMISORChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO_EMISOR = value;
					this.SendPropertyChanged("ID_USUARIO_EMISOR");
					this.OnID_USUARIO_EMISORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO_RECEPTOR", DbType="Int")]
		public System.Nullable<int> ID_USUARIO_RECEPTOR
		{
			get
			{
				return this._ID_USUARIO_RECEPTOR;
			}
			set
			{
				if ((this._ID_USUARIO_RECEPTOR != value))
				{
					if (this._USUARIO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USUARIO_RECEPTORChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO_RECEPTOR = value;
					this.SendPropertyChanged("ID_USUARIO_RECEPTOR");
					this.OnID_USUARIO_RECEPTORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMENTARIO_CORTA", DbType="VarChar(100)")]
		public string COMENTARIO_CORTA
		{
			get
			{
				return this._COMENTARIO_CORTA;
			}
			set
			{
				if ((this._COMENTARIO_CORTA != value))
				{
					this.OnCOMENTARIO_CORTAChanging(value);
					this.SendPropertyChanging();
					this._COMENTARIO_CORTA = value;
					this.SendPropertyChanged("COMENTARIO_CORTA");
					this.OnCOMENTARIO_CORTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMENTARIO_LARGO", DbType="VarChar(1000)")]
		public string COMENTARIO_LARGO
		{
			get
			{
				return this._COMENTARIO_LARGO;
			}
			set
			{
				if ((this._COMENTARIO_LARGO != value))
				{
					this.OnCOMENTARIO_LARGOChanging(value);
					this.SendPropertyChanging();
					this._COMENTARIO_LARGO = value;
					this.SendPropertyChanged("COMENTARIO_LARGO");
					this.OnCOMENTARIO_LARGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VALORACION", DbType="Int")]
		public System.Nullable<int> ID_VALORACION
		{
			get
			{
				return this._ID_VALORACION;
			}
			set
			{
				if ((this._ID_VALORACION != value))
				{
					if (this._VALORACIONE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_VALORACIONChanging(value);
					this.SendPropertyChanging();
					this._ID_VALORACION = value;
					this.SendPropertyChanged("ID_VALORACION");
					this.OnID_VALORACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INGRESO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_INGRESO
		{
			get
			{
				return this._FECHA_INGRESO;
			}
			set
			{
				if ((this._FECHA_INGRESO != value))
				{
					this.OnFECHA_INGRESOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INGRESO = value;
					this.SendPropertyChanged("FECHA_INGRESO");
					this.OnFECHA_INGRESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VALORACIONE_COMENTARIO", Storage="_VALORACIONE", ThisKey="ID_VALORACION", OtherKey="ID_VALORACION", IsForeignKey=true)]
		public VALORACIONE VALORACIONE
		{
			get
			{
				return this._VALORACIONE.Entity;
			}
			set
			{
				VALORACIONE previousValue = this._VALORACIONE.Entity;
				if (((previousValue != value) 
							|| (this._VALORACIONE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VALORACIONE.Entity = null;
						previousValue.COMENTARIOs.Remove(this);
					}
					this._VALORACIONE.Entity = value;
					if ((value != null))
					{
						value.COMENTARIOs.Add(this);
						this._ID_VALORACION = value.ID_VALORACION;
					}
					else
					{
						this._ID_VALORACION = default(Nullable<int>);
					}
					this.SendPropertyChanged("VALORACIONE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_COMENTARIO", Storage="_USUARIO", ThisKey="ID_USUARIO_EMISOR", OtherKey="ID_USUARIO", IsForeignKey=true)]
		public USUARIO USUARIO
		{
			get
			{
				return this._USUARIO.Entity;
			}
			set
			{
				USUARIO previousValue = this._USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USUARIO.Entity = null;
						previousValue.COMENTARIOs.Remove(this);
					}
					this._USUARIO.Entity = value;
					if ((value != null))
					{
						value.COMENTARIOs.Add(this);
						this._ID_USUARIO_EMISOR = value.ID_USUARIO;
					}
					else
					{
						this._ID_USUARIO_EMISOR = default(Nullable<int>);
					}
					this.SendPropertyChanged("USUARIO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_COMENTARIO1", Storage="_USUARIO1", ThisKey="ID_USUARIO_RECEPTOR", OtherKey="ID_USUARIO", IsForeignKey=true)]
		public USUARIO USUARIO1
		{
			get
			{
				return this._USUARIO1.Entity;
			}
			set
			{
				USUARIO previousValue = this._USUARIO1.Entity;
				if (((previousValue != value) 
							|| (this._USUARIO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USUARIO1.Entity = null;
						previousValue.COMENTARIOs1.Remove(this);
					}
					this._USUARIO1.Entity = value;
					if ((value != null))
					{
						value.COMENTARIOs1.Add(this);
						this._ID_USUARIO_RECEPTOR = value.ID_USUARIO;
					}
					else
					{
						this._ID_USUARIO_RECEPTOR = default(Nullable<int>);
					}
					this.SendPropertyChanged("USUARIO1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VALORACIONES")]
	public partial class VALORACIONE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_VALORACION;
		
		private System.Nullable<int> _VALORACION;
		
		private EntitySet<COMENTARIO> _COMENTARIOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VALORACIONChanging(int value);
    partial void OnID_VALORACIONChanged();
    partial void OnVALORACIONChanging(System.Nullable<int> value);
    partial void OnVALORACIONChanged();
    #endregion
		
		public VALORACIONE()
		{
			this._COMENTARIOs = new EntitySet<COMENTARIO>(new Action<COMENTARIO>(this.attach_COMENTARIOs), new Action<COMENTARIO>(this.detach_COMENTARIOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VALORACION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_VALORACION
		{
			get
			{
				return this._ID_VALORACION;
			}
			set
			{
				if ((this._ID_VALORACION != value))
				{
					this.OnID_VALORACIONChanging(value);
					this.SendPropertyChanging();
					this._ID_VALORACION = value;
					this.SendPropertyChanged("ID_VALORACION");
					this.OnID_VALORACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALORACION", DbType="Int")]
		public System.Nullable<int> VALORACION
		{
			get
			{
				return this._VALORACION;
			}
			set
			{
				if ((this._VALORACION != value))
				{
					this.OnVALORACIONChanging(value);
					this.SendPropertyChanging();
					this._VALORACION = value;
					this.SendPropertyChanged("VALORACION");
					this.OnVALORACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VALORACIONE_COMENTARIO", Storage="_COMENTARIOs", ThisKey="ID_VALORACION", OtherKey="ID_VALORACION")]
		public EntitySet<COMENTARIO> COMENTARIOs
		{
			get
			{
				return this._COMENTARIOs;
			}
			set
			{
				this._COMENTARIOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COMENTARIOs(COMENTARIO entity)
		{
			this.SendPropertyChanging();
			entity.VALORACIONE = this;
		}
		
		private void detach_COMENTARIOs(COMENTARIO entity)
		{
			this.SendPropertyChanging();
			entity.VALORACIONE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMPRESAS")]
	public partial class EMPRESA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_EMPRESA;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private string _DIRECCION;
		
		private string _TELEFONO;
		
		private string _EMAIL;
		
		private EntitySet<EXP_LABORALE> _EXP_LABORALEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EMPRESAChanging(int value);
    partial void OnID_EMPRESAChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public EMPRESA()
		{
			this._EXP_LABORALEs = new EntitySet<EXP_LABORALE>(new Action<EXP_LABORALE>(this.attach_EXP_LABORALEs), new Action<EXP_LABORALE>(this.detach_EXP_LABORALEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EMPRESA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_EMPRESA
		{
			get
			{
				return this._ID_EMPRESA;
			}
			set
			{
				if ((this._ID_EMPRESA != value))
				{
					this.OnID_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._ID_EMPRESA = value;
					this.SendPropertyChanged("ID_EMPRESA");
					this.OnID_EMPRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(100)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(100)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(100)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EMPRESA_EXP_LABORALE", Storage="_EXP_LABORALEs", ThisKey="ID_EMPRESA", OtherKey="ID_EMPRESA")]
		public EntitySet<EXP_LABORALE> EXP_LABORALEs
		{
			get
			{
				return this._EXP_LABORALEs;
			}
			set
			{
				this._EXP_LABORALEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EXP_LABORALEs(EXP_LABORALE entity)
		{
			this.SendPropertyChanging();
			entity.EMPRESA = this;
		}
		
		private void detach_EXP_LABORALEs(EXP_LABORALE entity)
		{
			this.SendPropertyChanging();
			entity.EMPRESA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EXP_EDUCACIONALES")]
	public partial class EXP_EDUCACIONALE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_EXP_EDUCACION;
		
		private System.Nullable<System.DateTime> _FECHA_INICIO;
		
		private System.Nullable<System.DateTime> _FECHA_TERMINO;
		
		private System.Nullable<int> _ID_INSTITUCION;
		
		private System.Nullable<int> _ID_USUARIO;
		
		private string _DESCRIPCION;
		
		private EntityRef<INSTITUCIONE> _INSTITUCIONE;
		
		private EntityRef<USUARIO> _USUARIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EXP_EDUCACIONChanging(int value);
    partial void OnID_EXP_EDUCACIONChanged();
    partial void OnFECHA_INICIOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_INICIOChanged();
    partial void OnFECHA_TERMINOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_TERMINOChanged();
    partial void OnID_INSTITUCIONChanging(System.Nullable<int> value);
    partial void OnID_INSTITUCIONChanged();
    partial void OnID_USUARIOChanging(System.Nullable<int> value);
    partial void OnID_USUARIOChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    #endregion
		
		public EXP_EDUCACIONALE()
		{
			this._INSTITUCIONE = default(EntityRef<INSTITUCIONE>);
			this._USUARIO = default(EntityRef<USUARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EXP_EDUCACION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_EXP_EDUCACION
		{
			get
			{
				return this._ID_EXP_EDUCACION;
			}
			set
			{
				if ((this._ID_EXP_EDUCACION != value))
				{
					this.OnID_EXP_EDUCACIONChanging(value);
					this.SendPropertyChanging();
					this._ID_EXP_EDUCACION = value;
					this.SendPropertyChanged("ID_EXP_EDUCACION");
					this.OnID_EXP_EDUCACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INICIO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_INICIO
		{
			get
			{
				return this._FECHA_INICIO;
			}
			set
			{
				if ((this._FECHA_INICIO != value))
				{
					this.OnFECHA_INICIOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INICIO = value;
					this.SendPropertyChanged("FECHA_INICIO");
					this.OnFECHA_INICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TERMINO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_TERMINO
		{
			get
			{
				return this._FECHA_TERMINO;
			}
			set
			{
				if ((this._FECHA_TERMINO != value))
				{
					this.OnFECHA_TERMINOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_TERMINO = value;
					this.SendPropertyChanged("FECHA_TERMINO");
					this.OnFECHA_TERMINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSTITUCION", DbType="Int")]
		public System.Nullable<int> ID_INSTITUCION
		{
			get
			{
				return this._ID_INSTITUCION;
			}
			set
			{
				if ((this._ID_INSTITUCION != value))
				{
					if (this._INSTITUCIONE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_INSTITUCIONChanging(value);
					this.SendPropertyChanging();
					this._ID_INSTITUCION = value;
					this.SendPropertyChanged("ID_INSTITUCION");
					this.OnID_INSTITUCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int")]
		public System.Nullable<int> ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					if (this._USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(200)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INSTITUCIONE_EXP_EDUCACIONALE", Storage="_INSTITUCIONE", ThisKey="ID_INSTITUCION", OtherKey="ID_INSTITUCION", IsForeignKey=true)]
		public INSTITUCIONE INSTITUCIONE
		{
			get
			{
				return this._INSTITUCIONE.Entity;
			}
			set
			{
				INSTITUCIONE previousValue = this._INSTITUCIONE.Entity;
				if (((previousValue != value) 
							|| (this._INSTITUCIONE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._INSTITUCIONE.Entity = null;
						previousValue.EXP_EDUCACIONALEs.Remove(this);
					}
					this._INSTITUCIONE.Entity = value;
					if ((value != null))
					{
						value.EXP_EDUCACIONALEs.Add(this);
						this._ID_INSTITUCION = value.ID_INSTITUCION;
					}
					else
					{
						this._ID_INSTITUCION = default(Nullable<int>);
					}
					this.SendPropertyChanged("INSTITUCIONE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_EXP_EDUCACIONALE", Storage="_USUARIO", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO", IsForeignKey=true)]
		public USUARIO USUARIO
		{
			get
			{
				return this._USUARIO.Entity;
			}
			set
			{
				USUARIO previousValue = this._USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USUARIO.Entity = null;
						previousValue.EXP_EDUCACIONALEs.Remove(this);
					}
					this._USUARIO.Entity = value;
					if ((value != null))
					{
						value.EXP_EDUCACIONALEs.Add(this);
						this._ID_USUARIO = value.ID_USUARIO;
					}
					else
					{
						this._ID_USUARIO = default(Nullable<int>);
					}
					this.SendPropertyChanged("USUARIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EXP_EMPRENDEDORES")]
	public partial class EXP_EMPRENDEDORE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_EXP_EMPRENDEDOR;
		
		private System.Nullable<System.DateTime> _FECHA_INICIO;
		
		private System.Nullable<System.DateTime> _FECHA_TERMINO;
		
		private System.Nullable<int> _ID_PROYECTO;
		
		private System.Nullable<int> _ID_ROL;
		
		private System.Nullable<int> _ID_USUARIO;
		
		private int _DESCRIPCION;
		
		private EntityRef<PROYECTO> _PROYECTO;
		
		private EntityRef<ROLE> _ROLE;
		
		private EntityRef<USUARIO> _USUARIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EXP_EMPRENDEDORChanging(int value);
    partial void OnID_EXP_EMPRENDEDORChanged();
    partial void OnFECHA_INICIOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_INICIOChanged();
    partial void OnFECHA_TERMINOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_TERMINOChanged();
    partial void OnID_PROYECTOChanging(System.Nullable<int> value);
    partial void OnID_PROYECTOChanged();
    partial void OnID_ROLChanging(System.Nullable<int> value);
    partial void OnID_ROLChanged();
    partial void OnID_USUARIOChanging(System.Nullable<int> value);
    partial void OnID_USUARIOChanged();
    partial void OnDESCRIPCIONChanging(int value);
    partial void OnDESCRIPCIONChanged();
    #endregion
		
		public EXP_EMPRENDEDORE()
		{
			this._PROYECTO = default(EntityRef<PROYECTO>);
			this._ROLE = default(EntityRef<ROLE>);
			this._USUARIO = default(EntityRef<USUARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EXP_EMPRENDEDOR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_EXP_EMPRENDEDOR
		{
			get
			{
				return this._ID_EXP_EMPRENDEDOR;
			}
			set
			{
				if ((this._ID_EXP_EMPRENDEDOR != value))
				{
					this.OnID_EXP_EMPRENDEDORChanging(value);
					this.SendPropertyChanging();
					this._ID_EXP_EMPRENDEDOR = value;
					this.SendPropertyChanged("ID_EXP_EMPRENDEDOR");
					this.OnID_EXP_EMPRENDEDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INICIO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_INICIO
		{
			get
			{
				return this._FECHA_INICIO;
			}
			set
			{
				if ((this._FECHA_INICIO != value))
				{
					this.OnFECHA_INICIOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INICIO = value;
					this.SendPropertyChanged("FECHA_INICIO");
					this.OnFECHA_INICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TERMINO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_TERMINO
		{
			get
			{
				return this._FECHA_TERMINO;
			}
			set
			{
				if ((this._FECHA_TERMINO != value))
				{
					this.OnFECHA_TERMINOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_TERMINO = value;
					this.SendPropertyChanged("FECHA_TERMINO");
					this.OnFECHA_TERMINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROYECTO", DbType="Int")]
		public System.Nullable<int> ID_PROYECTO
		{
			get
			{
				return this._ID_PROYECTO;
			}
			set
			{
				if ((this._ID_PROYECTO != value))
				{
					if (this._PROYECTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PROYECTOChanging(value);
					this.SendPropertyChanging();
					this._ID_PROYECTO = value;
					this.SendPropertyChanged("ID_PROYECTO");
					this.OnID_PROYECTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ROL", DbType="Int")]
		public System.Nullable<int> ID_ROL
		{
			get
			{
				return this._ID_ROL;
			}
			set
			{
				if ((this._ID_ROL != value))
				{
					if (this._ROLE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ROLChanging(value);
					this.SendPropertyChanging();
					this._ID_ROL = value;
					this.SendPropertyChanged("ID_ROL");
					this.OnID_ROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int")]
		public System.Nullable<int> ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					if (this._USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="Int NOT NULL")]
		public int DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROYECTO_EXP_EMPRENDEDORE", Storage="_PROYECTO", ThisKey="ID_PROYECTO", OtherKey="ID_PROYECTO", IsForeignKey=true)]
		public PROYECTO PROYECTO
		{
			get
			{
				return this._PROYECTO.Entity;
			}
			set
			{
				PROYECTO previousValue = this._PROYECTO.Entity;
				if (((previousValue != value) 
							|| (this._PROYECTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROYECTO.Entity = null;
						previousValue.EXP_EMPRENDEDOREs.Remove(this);
					}
					this._PROYECTO.Entity = value;
					if ((value != null))
					{
						value.EXP_EMPRENDEDOREs.Add(this);
						this._ID_PROYECTO = value.ID_PROYECTO;
					}
					else
					{
						this._ID_PROYECTO = default(Nullable<int>);
					}
					this.SendPropertyChanged("PROYECTO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROLE_EXP_EMPRENDEDORE", Storage="_ROLE", ThisKey="ID_ROL", OtherKey="ID_ROL", IsForeignKey=true)]
		public ROLE ROLE
		{
			get
			{
				return this._ROLE.Entity;
			}
			set
			{
				ROLE previousValue = this._ROLE.Entity;
				if (((previousValue != value) 
							|| (this._ROLE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ROLE.Entity = null;
						previousValue.EXP_EMPRENDEDOREs.Remove(this);
					}
					this._ROLE.Entity = value;
					if ((value != null))
					{
						value.EXP_EMPRENDEDOREs.Add(this);
						this._ID_ROL = value.ID_ROL;
					}
					else
					{
						this._ID_ROL = default(Nullable<int>);
					}
					this.SendPropertyChanged("ROLE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_EXP_EMPRENDEDORE", Storage="_USUARIO", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO", IsForeignKey=true)]
		public USUARIO USUARIO
		{
			get
			{
				return this._USUARIO.Entity;
			}
			set
			{
				USUARIO previousValue = this._USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USUARIO.Entity = null;
						previousValue.EXP_EMPRENDEDOREs.Remove(this);
					}
					this._USUARIO.Entity = value;
					if ((value != null))
					{
						value.EXP_EMPRENDEDOREs.Add(this);
						this._ID_USUARIO = value.ID_USUARIO;
					}
					else
					{
						this._ID_USUARIO = default(Nullable<int>);
					}
					this.SendPropertyChanged("USUARIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EXP_LABORALES")]
	public partial class EXP_LABORALE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_EXP_LABORAL;
		
		private System.Nullable<int> _ID_ROL;
		
		private System.Nullable<System.DateTime> _FECHA_INICIO;
		
		private System.Nullable<System.DateTime> _FECHA_TERMINO;
		
		private System.Nullable<int> _ID_EMPRESA;
		
		private string _DESCRIPCION;
		
		private EntityRef<EMPRESA> _EMPRESA;
		
		private EntityRef<ROLE> _ROLE;
		
		private EntityRef<USUARIO> _USUARIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EXP_LABORALChanging(int value);
    partial void OnID_EXP_LABORALChanged();
    partial void OnID_ROLChanging(System.Nullable<int> value);
    partial void OnID_ROLChanged();
    partial void OnFECHA_INICIOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_INICIOChanged();
    partial void OnFECHA_TERMINOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_TERMINOChanged();
    partial void OnID_EMPRESAChanging(System.Nullable<int> value);
    partial void OnID_EMPRESAChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    #endregion
		
		public EXP_LABORALE()
		{
			this._EMPRESA = default(EntityRef<EMPRESA>);
			this._ROLE = default(EntityRef<ROLE>);
			this._USUARIO = default(EntityRef<USUARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EXP_LABORAL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_EXP_LABORAL
		{
			get
			{
				return this._ID_EXP_LABORAL;
			}
			set
			{
				if ((this._ID_EXP_LABORAL != value))
				{
					if (this._USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EXP_LABORALChanging(value);
					this.SendPropertyChanging();
					this._ID_EXP_LABORAL = value;
					this.SendPropertyChanged("ID_EXP_LABORAL");
					this.OnID_EXP_LABORALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ROL", DbType="Int")]
		public System.Nullable<int> ID_ROL
		{
			get
			{
				return this._ID_ROL;
			}
			set
			{
				if ((this._ID_ROL != value))
				{
					if (this._ROLE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ROLChanging(value);
					this.SendPropertyChanging();
					this._ID_ROL = value;
					this.SendPropertyChanged("ID_ROL");
					this.OnID_ROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INICIO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_INICIO
		{
			get
			{
				return this._FECHA_INICIO;
			}
			set
			{
				if ((this._FECHA_INICIO != value))
				{
					this.OnFECHA_INICIOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INICIO = value;
					this.SendPropertyChanged("FECHA_INICIO");
					this.OnFECHA_INICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_TERMINO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_TERMINO
		{
			get
			{
				return this._FECHA_TERMINO;
			}
			set
			{
				if ((this._FECHA_TERMINO != value))
				{
					this.OnFECHA_TERMINOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_TERMINO = value;
					this.SendPropertyChanged("FECHA_TERMINO");
					this.OnFECHA_TERMINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EMPRESA", DbType="Int")]
		public System.Nullable<int> ID_EMPRESA
		{
			get
			{
				return this._ID_EMPRESA;
			}
			set
			{
				if ((this._ID_EMPRESA != value))
				{
					if (this._EMPRESA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._ID_EMPRESA = value;
					this.SendPropertyChanged("ID_EMPRESA");
					this.OnID_EMPRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(MAX)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EMPRESA_EXP_LABORALE", Storage="_EMPRESA", ThisKey="ID_EMPRESA", OtherKey="ID_EMPRESA", IsForeignKey=true)]
		public EMPRESA EMPRESA
		{
			get
			{
				return this._EMPRESA.Entity;
			}
			set
			{
				EMPRESA previousValue = this._EMPRESA.Entity;
				if (((previousValue != value) 
							|| (this._EMPRESA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EMPRESA.Entity = null;
						previousValue.EXP_LABORALEs.Remove(this);
					}
					this._EMPRESA.Entity = value;
					if ((value != null))
					{
						value.EXP_LABORALEs.Add(this);
						this._ID_EMPRESA = value.ID_EMPRESA;
					}
					else
					{
						this._ID_EMPRESA = default(Nullable<int>);
					}
					this.SendPropertyChanged("EMPRESA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROLE_EXP_LABORALE", Storage="_ROLE", ThisKey="ID_ROL", OtherKey="ID_ROL", IsForeignKey=true)]
		public ROLE ROLE
		{
			get
			{
				return this._ROLE.Entity;
			}
			set
			{
				ROLE previousValue = this._ROLE.Entity;
				if (((previousValue != value) 
							|| (this._ROLE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ROLE.Entity = null;
						previousValue.EXP_LABORALEs.Remove(this);
					}
					this._ROLE.Entity = value;
					if ((value != null))
					{
						value.EXP_LABORALEs.Add(this);
						this._ID_ROL = value.ID_ROL;
					}
					else
					{
						this._ID_ROL = default(Nullable<int>);
					}
					this.SendPropertyChanged("ROLE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_EXP_LABORALE", Storage="_USUARIO", ThisKey="ID_EXP_LABORAL", OtherKey="ID_USUARIO", IsForeignKey=true)]
		public USUARIO USUARIO
		{
			get
			{
				return this._USUARIO.Entity;
			}
			set
			{
				USUARIO previousValue = this._USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USUARIO.Entity = null;
						previousValue.EXP_LABORALE = null;
					}
					this._USUARIO.Entity = value;
					if ((value != null))
					{
						value.EXP_LABORALE = this;
						this._ID_EXP_LABORAL = value.ID_USUARIO;
					}
					else
					{
						this._ID_EXP_LABORAL = default(int);
					}
					this.SendPropertyChanged("USUARIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HABILIDADES")]
	public partial class HABILIDADE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_HABILIDAD;
		
		private string _NOMBRE_HABLIDIDAD;
		
		private System.Data.Linq.Binary _TIMESTAMP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HABILIDADChanging(int value);
    partial void OnID_HABILIDADChanged();
    partial void OnNOMBRE_HABLIDIDADChanging(string value);
    partial void OnNOMBRE_HABLIDIDADChanged();
    partial void OnTIMESTAMPChanging(System.Data.Linq.Binary value);
    partial void OnTIMESTAMPChanged();
    #endregion
		
		public HABILIDADE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HABILIDAD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ID_HABILIDAD
		{
			get
			{
				return this._ID_HABILIDAD;
			}
			set
			{
				if ((this._ID_HABILIDAD != value))
				{
					this.OnID_HABILIDADChanging(value);
					this.SendPropertyChanging();
					this._ID_HABILIDAD = value;
					this.SendPropertyChanged("ID_HABILIDAD");
					this.OnID_HABILIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_HABLIDIDAD", DbType="NChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string NOMBRE_HABLIDIDAD
		{
			get
			{
				return this._NOMBRE_HABLIDIDAD;
			}
			set
			{
				if ((this._NOMBRE_HABLIDIDAD != value))
				{
					this.OnNOMBRE_HABLIDIDADChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_HABLIDIDAD = value;
					this.SendPropertyChanged("NOMBRE_HABLIDIDAD");
					this.OnNOMBRE_HABLIDIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMESTAMP", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary TIMESTAMP
		{
			get
			{
				return this._TIMESTAMP;
			}
			set
			{
				if ((this._TIMESTAMP != value))
				{
					this.OnTIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._TIMESTAMP = value;
					this.SendPropertyChanged("TIMESTAMP");
					this.OnTIMESTAMPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HABILIDADES_USUARIOS")]
	public partial class HABILIDADES_USUARIO
	{
		
		private System.Nullable<int> _ID_USUARIO;
		
		private System.Nullable<int> _ID_HABLIIDADES;
		
		public HABILIDADES_USUARIO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int")]
		public System.Nullable<int> ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this._ID_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HABLIIDADES", DbType="Int")]
		public System.Nullable<int> ID_HABLIIDADES
		{
			get
			{
				return this._ID_HABLIIDADES;
			}
			set
			{
				if ((this._ID_HABLIIDADES != value))
				{
					this._ID_HABLIIDADES = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INSTITUCIONES")]
	public partial class INSTITUCIONE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_INSTITUCION;
		
		private string _NOMBRE_INSTITUCION;
		
		private string _DIRECCION;
		
		private string _TELEFONO;
		
		private string _EMAIL;
		
		private EntitySet<EXP_EDUCACIONALE> _EXP_EDUCACIONALEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_INSTITUCIONChanging(int value);
    partial void OnID_INSTITUCIONChanged();
    partial void OnNOMBRE_INSTITUCIONChanging(string value);
    partial void OnNOMBRE_INSTITUCIONChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public INSTITUCIONE()
		{
			this._EXP_EDUCACIONALEs = new EntitySet<EXP_EDUCACIONALE>(new Action<EXP_EDUCACIONALE>(this.attach_EXP_EDUCACIONALEs), new Action<EXP_EDUCACIONALE>(this.detach_EXP_EDUCACIONALEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSTITUCION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_INSTITUCION
		{
			get
			{
				return this._ID_INSTITUCION;
			}
			set
			{
				if ((this._ID_INSTITUCION != value))
				{
					this.OnID_INSTITUCIONChanging(value);
					this.SendPropertyChanging();
					this._ID_INSTITUCION = value;
					this.SendPropertyChanged("ID_INSTITUCION");
					this.OnID_INSTITUCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_INSTITUCION", DbType="VarChar(100)")]
		public string NOMBRE_INSTITUCION
		{
			get
			{
				return this._NOMBRE_INSTITUCION;
			}
			set
			{
				if ((this._NOMBRE_INSTITUCION != value))
				{
					this.OnNOMBRE_INSTITUCIONChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_INSTITUCION = value;
					this.SendPropertyChanged("NOMBRE_INSTITUCION");
					this.OnNOMBRE_INSTITUCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(100)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(50)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INSTITUCIONE_EXP_EDUCACIONALE", Storage="_EXP_EDUCACIONALEs", ThisKey="ID_INSTITUCION", OtherKey="ID_INSTITUCION")]
		public EntitySet<EXP_EDUCACIONALE> EXP_EDUCACIONALEs
		{
			get
			{
				return this._EXP_EDUCACIONALEs;
			}
			set
			{
				this._EXP_EDUCACIONALEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EXP_EDUCACIONALEs(EXP_EDUCACIONALE entity)
		{
			this.SendPropertyChanging();
			entity.INSTITUCIONE = this;
		}
		
		private void detach_EXP_EDUCACIONALEs(EXP_EDUCACIONALE entity)
		{
			this.SendPropertyChanging();
			entity.INSTITUCIONE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOG_ERRORES")]
	public partial class LOG_ERRORE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOG;
		
		private string _DESCRIPCION;
		
		private System.Nullable<int> _ID_NIVEL_ERROR;
		
		private System.Nullable<System.DateTime> _FECHA_INGRESO;
		
		private System.Data.Linq.Binary _TIMESTAMP;
		
		private EntityRef<NIVEL_ERRORE> _NIVEL_ERRORE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOGChanging(int value);
    partial void OnID_LOGChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnID_NIVEL_ERRORChanging(System.Nullable<int> value);
    partial void OnID_NIVEL_ERRORChanged();
    partial void OnFECHA_INGRESOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_INGRESOChanged();
    partial void OnTIMESTAMPChanging(System.Data.Linq.Binary value);
    partial void OnTIMESTAMPChanged();
    #endregion
		
		public LOG_ERRORE()
		{
			this._NIVEL_ERRORE = default(EntityRef<NIVEL_ERRORE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ID_LOG
		{
			get
			{
				return this._ID_LOG;
			}
			set
			{
				if ((this._ID_LOG != value))
				{
					this.OnID_LOGChanging(value);
					this.SendPropertyChanging();
					this._ID_LOG = value;
					this.SendPropertyChanged("ID_LOG");
					this.OnID_LOGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NIVEL_ERROR", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ID_NIVEL_ERROR
		{
			get
			{
				return this._ID_NIVEL_ERROR;
			}
			set
			{
				if ((this._ID_NIVEL_ERROR != value))
				{
					if (this._NIVEL_ERRORE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NIVEL_ERRORChanging(value);
					this.SendPropertyChanging();
					this._ID_NIVEL_ERROR = value;
					this.SendPropertyChanged("ID_NIVEL_ERROR");
					this.OnID_NIVEL_ERRORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INGRESO", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> FECHA_INGRESO
		{
			get
			{
				return this._FECHA_INGRESO;
			}
			set
			{
				if ((this._FECHA_INGRESO != value))
				{
					this.OnFECHA_INGRESOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INGRESO = value;
					this.SendPropertyChanged("FECHA_INGRESO");
					this.OnFECHA_INGRESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMESTAMP", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary TIMESTAMP
		{
			get
			{
				return this._TIMESTAMP;
			}
			set
			{
				if ((this._TIMESTAMP != value))
				{
					this.OnTIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._TIMESTAMP = value;
					this.SendPropertyChanged("TIMESTAMP");
					this.OnTIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NIVEL_ERRORE_LOG_ERRORE", Storage="_NIVEL_ERRORE", ThisKey="ID_NIVEL_ERROR", OtherKey="ID_NIVEL_ERROR", IsForeignKey=true)]
		public NIVEL_ERRORE NIVEL_ERRORE
		{
			get
			{
				return this._NIVEL_ERRORE.Entity;
			}
			set
			{
				NIVEL_ERRORE previousValue = this._NIVEL_ERRORE.Entity;
				if (((previousValue != value) 
							|| (this._NIVEL_ERRORE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NIVEL_ERRORE.Entity = null;
						previousValue.LOG_ERROREs.Remove(this);
					}
					this._NIVEL_ERRORE.Entity = value;
					if ((value != null))
					{
						value.LOG_ERROREs.Add(this);
						this._ID_NIVEL_ERROR = value.ID_NIVEL_ERROR;
					}
					else
					{
						this._ID_NIVEL_ERROR = default(Nullable<int>);
					}
					this.SendPropertyChanged("NIVEL_ERRORE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NIVEL_ERRORES")]
	public partial class NIVEL_ERRORE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_NIVEL_ERROR;
		
		private string _NIVEL;
		
		private string _DESCRIPCION;
		
		private System.Data.Linq.Binary _TIMESTAMP;
		
		private EntitySet<LOG_ERRORE> _LOG_ERROREs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NIVEL_ERRORChanging(int value);
    partial void OnID_NIVEL_ERRORChanged();
    partial void OnNIVELChanging(string value);
    partial void OnNIVELChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnTIMESTAMPChanging(System.Data.Linq.Binary value);
    partial void OnTIMESTAMPChanged();
    #endregion
		
		public NIVEL_ERRORE()
		{
			this._LOG_ERROREs = new EntitySet<LOG_ERRORE>(new Action<LOG_ERRORE>(this.attach_LOG_ERROREs), new Action<LOG_ERRORE>(this.detach_LOG_ERROREs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NIVEL_ERROR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ID_NIVEL_ERROR
		{
			get
			{
				return this._ID_NIVEL_ERROR;
			}
			set
			{
				if ((this._ID_NIVEL_ERROR != value))
				{
					this.OnID_NIVEL_ERRORChanging(value);
					this.SendPropertyChanging();
					this._ID_NIVEL_ERROR = value;
					this.SendPropertyChanged("ID_NIVEL_ERROR");
					this.OnID_NIVEL_ERRORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL", DbType="VarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string NIVEL
		{
			get
			{
				return this._NIVEL;
			}
			set
			{
				if ((this._NIVEL != value))
				{
					this.OnNIVELChanging(value);
					this.SendPropertyChanging();
					this._NIVEL = value;
					this.SendPropertyChanged("NIVEL");
					this.OnNIVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMESTAMP", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary TIMESTAMP
		{
			get
			{
				return this._TIMESTAMP;
			}
			set
			{
				if ((this._TIMESTAMP != value))
				{
					this.OnTIMESTAMPChanging(value);
					this.SendPropertyChanging();
					this._TIMESTAMP = value;
					this.SendPropertyChanged("TIMESTAMP");
					this.OnTIMESTAMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NIVEL_ERRORE_LOG_ERRORE", Storage="_LOG_ERROREs", ThisKey="ID_NIVEL_ERROR", OtherKey="ID_NIVEL_ERROR")]
		public EntitySet<LOG_ERRORE> LOG_ERROREs
		{
			get
			{
				return this._LOG_ERROREs;
			}
			set
			{
				this._LOG_ERROREs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LOG_ERROREs(LOG_ERRORE entity)
		{
			this.SendPropertyChanging();
			entity.NIVEL_ERRORE = this;
		}
		
		private void detach_LOG_ERROREs(LOG_ERRORE entity)
		{
			this.SendPropertyChanging();
			entity.NIVEL_ERRORE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROFESIONES")]
	public partial class PROFESIONE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PROFESION;
		
		private string _NOMBRE_PROFESION;
		
		private EntitySet<USUARIO> _USUARIOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PROFESIONChanging(int value);
    partial void OnID_PROFESIONChanged();
    partial void OnNOMBRE_PROFESIONChanging(string value);
    partial void OnNOMBRE_PROFESIONChanged();
    #endregion
		
		public PROFESIONE()
		{
			this._USUARIOs = new EntitySet<USUARIO>(new Action<USUARIO>(this.attach_USUARIOs), new Action<USUARIO>(this.detach_USUARIOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROFESION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PROFESION
		{
			get
			{
				return this._ID_PROFESION;
			}
			set
			{
				if ((this._ID_PROFESION != value))
				{
					this.OnID_PROFESIONChanging(value);
					this.SendPropertyChanging();
					this._ID_PROFESION = value;
					this.SendPropertyChanged("ID_PROFESION");
					this.OnID_PROFESIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PROFESION", DbType="VarChar(100)")]
		public string NOMBRE_PROFESION
		{
			get
			{
				return this._NOMBRE_PROFESION;
			}
			set
			{
				if ((this._NOMBRE_PROFESION != value))
				{
					this.OnNOMBRE_PROFESIONChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_PROFESION = value;
					this.SendPropertyChanged("NOMBRE_PROFESION");
					this.OnNOMBRE_PROFESIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESIONE_USUARIO", Storage="_USUARIOs", ThisKey="ID_PROFESION", OtherKey="ID_PROFESION")]
		public EntitySet<USUARIO> USUARIOs
		{
			get
			{
				return this._USUARIOs;
			}
			set
			{
				this._USUARIOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_USUARIOs(USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.PROFESIONE = this;
		}
		
		private void detach_USUARIOs(USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.PROFESIONE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROYECTOS")]
	public partial class PROYECTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PROYECTO;
		
		private string _NOMBRE_PROYECTO;
		
		private string _DESCRIPCION_PROYECTO;
		
		private EntitySet<EXP_EMPRENDEDORE> _EXP_EMPRENDEDOREs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PROYECTOChanging(int value);
    partial void OnID_PROYECTOChanged();
    partial void OnNOMBRE_PROYECTOChanging(string value);
    partial void OnNOMBRE_PROYECTOChanged();
    partial void OnDESCRIPCION_PROYECTOChanging(string value);
    partial void OnDESCRIPCION_PROYECTOChanged();
    #endregion
		
		public PROYECTO()
		{
			this._EXP_EMPRENDEDOREs = new EntitySet<EXP_EMPRENDEDORE>(new Action<EXP_EMPRENDEDORE>(this.attach_EXP_EMPRENDEDOREs), new Action<EXP_EMPRENDEDORE>(this.detach_EXP_EMPRENDEDOREs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROYECTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PROYECTO
		{
			get
			{
				return this._ID_PROYECTO;
			}
			set
			{
				if ((this._ID_PROYECTO != value))
				{
					this.OnID_PROYECTOChanging(value);
					this.SendPropertyChanging();
					this._ID_PROYECTO = value;
					this.SendPropertyChanged("ID_PROYECTO");
					this.OnID_PROYECTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PROYECTO", DbType="VarChar(100)")]
		public string NOMBRE_PROYECTO
		{
			get
			{
				return this._NOMBRE_PROYECTO;
			}
			set
			{
				if ((this._NOMBRE_PROYECTO != value))
				{
					this.OnNOMBRE_PROYECTOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_PROYECTO = value;
					this.SendPropertyChanged("NOMBRE_PROYECTO");
					this.OnNOMBRE_PROYECTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION_PROYECTO", DbType="VarChar(MAX)")]
		public string DESCRIPCION_PROYECTO
		{
			get
			{
				return this._DESCRIPCION_PROYECTO;
			}
			set
			{
				if ((this._DESCRIPCION_PROYECTO != value))
				{
					this.OnDESCRIPCION_PROYECTOChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION_PROYECTO = value;
					this.SendPropertyChanged("DESCRIPCION_PROYECTO");
					this.OnDESCRIPCION_PROYECTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROYECTO_EXP_EMPRENDEDORE", Storage="_EXP_EMPRENDEDOREs", ThisKey="ID_PROYECTO", OtherKey="ID_PROYECTO")]
		public EntitySet<EXP_EMPRENDEDORE> EXP_EMPRENDEDOREs
		{
			get
			{
				return this._EXP_EMPRENDEDOREs;
			}
			set
			{
				this._EXP_EMPRENDEDOREs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EXP_EMPRENDEDOREs(EXP_EMPRENDEDORE entity)
		{
			this.SendPropertyChanging();
			entity.PROYECTO = this;
		}
		
		private void detach_EXP_EMPRENDEDOREs(EXP_EMPRENDEDORE entity)
		{
			this.SendPropertyChanging();
			entity.PROYECTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ROLES")]
	public partial class ROLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ROL;
		
		private string _NOMBRE_ROL;
		
		private string _DESCRIPCION;
		
		private EntitySet<EXP_EMPRENDEDORE> _EXP_EMPRENDEDOREs;
		
		private EntitySet<EXP_LABORALE> _EXP_LABORALEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ROLChanging(int value);
    partial void OnID_ROLChanged();
    partial void OnNOMBRE_ROLChanging(string value);
    partial void OnNOMBRE_ROLChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    #endregion
		
		public ROLE()
		{
			this._EXP_EMPRENDEDOREs = new EntitySet<EXP_EMPRENDEDORE>(new Action<EXP_EMPRENDEDORE>(this.attach_EXP_EMPRENDEDOREs), new Action<EXP_EMPRENDEDORE>(this.detach_EXP_EMPRENDEDOREs));
			this._EXP_LABORALEs = new EntitySet<EXP_LABORALE>(new Action<EXP_LABORALE>(this.attach_EXP_LABORALEs), new Action<EXP_LABORALE>(this.detach_EXP_LABORALEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ROL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ROL
		{
			get
			{
				return this._ID_ROL;
			}
			set
			{
				if ((this._ID_ROL != value))
				{
					this.OnID_ROLChanging(value);
					this.SendPropertyChanging();
					this._ID_ROL = value;
					this.SendPropertyChanged("ID_ROL");
					this.OnID_ROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_ROL", DbType="VarChar(100)")]
		public string NOMBRE_ROL
		{
			get
			{
				return this._NOMBRE_ROL;
			}
			set
			{
				if ((this._NOMBRE_ROL != value))
				{
					this.OnNOMBRE_ROLChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_ROL = value;
					this.SendPropertyChanged("NOMBRE_ROL");
					this.OnNOMBRE_ROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(100)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROLE_EXP_EMPRENDEDORE", Storage="_EXP_EMPRENDEDOREs", ThisKey="ID_ROL", OtherKey="ID_ROL")]
		public EntitySet<EXP_EMPRENDEDORE> EXP_EMPRENDEDOREs
		{
			get
			{
				return this._EXP_EMPRENDEDOREs;
			}
			set
			{
				this._EXP_EMPRENDEDOREs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROLE_EXP_LABORALE", Storage="_EXP_LABORALEs", ThisKey="ID_ROL", OtherKey="ID_ROL")]
		public EntitySet<EXP_LABORALE> EXP_LABORALEs
		{
			get
			{
				return this._EXP_LABORALEs;
			}
			set
			{
				this._EXP_LABORALEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EXP_EMPRENDEDOREs(EXP_EMPRENDEDORE entity)
		{
			this.SendPropertyChanging();
			entity.ROLE = this;
		}
		
		private void detach_EXP_EMPRENDEDOREs(EXP_EMPRENDEDORE entity)
		{
			this.SendPropertyChanging();
			entity.ROLE = null;
		}
		
		private void attach_EXP_LABORALEs(EXP_LABORALE entity)
		{
			this.SendPropertyChanging();
			entity.ROLE = this;
		}
		
		private void detach_EXP_LABORALEs(EXP_LABORALE entity)
		{
			this.SendPropertyChanging();
			entity.ROLE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIOS")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USUARIO;
		
		private string _NOMBRE;
		
		private string _APELLIDO_PATERNO;
		
		private string _APELLIDO_MATERNO;
		
		private string _FECHA_NACIMIENTO;
		
		private string _EMAIL;
		
		private string _TELEFONO_PERSONAL;
		
		private string _TELEFONO_CELULAR;
		
		private string _USUARIO1;
		
		private string _PASSWORD;
		
		private System.Nullable<int> _ID_PROFESION;
		
		private EntitySet<COMENTARIO> _COMENTARIOs;
		
		private EntitySet<COMENTARIO> _COMENTARIOs1;
		
		private EntitySet<EXP_EDUCACIONALE> _EXP_EDUCACIONALEs;
		
		private EntitySet<EXP_EMPRENDEDORE> _EXP_EMPRENDEDOREs;
		
		private EntityRef<EXP_LABORALE> _EXP_LABORALE;
		
		private EntityRef<PROFESIONE> _PROFESIONE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USUARIOChanging(int value);
    partial void OnID_USUARIOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnAPELLIDO_PATERNOChanging(string value);
    partial void OnAPELLIDO_PATERNOChanged();
    partial void OnAPELLIDO_MATERNOChanging(string value);
    partial void OnAPELLIDO_MATERNOChanged();
    partial void OnFECHA_NACIMIENTOChanging(string value);
    partial void OnFECHA_NACIMIENTOChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnTELEFONO_PERSONALChanging(string value);
    partial void OnTELEFONO_PERSONALChanged();
    partial void OnTELEFONO_CELULARChanging(string value);
    partial void OnTELEFONO_CELULARChanged();
    partial void OnUSUARIO1Changing(string value);
    partial void OnUSUARIO1Changed();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnID_PROFESIONChanging(System.Nullable<int> value);
    partial void OnID_PROFESIONChanged();
    #endregion
		
		public USUARIO()
		{
			this._COMENTARIOs = new EntitySet<COMENTARIO>(new Action<COMENTARIO>(this.attach_COMENTARIOs), new Action<COMENTARIO>(this.detach_COMENTARIOs));
			this._COMENTARIOs1 = new EntitySet<COMENTARIO>(new Action<COMENTARIO>(this.attach_COMENTARIOs1), new Action<COMENTARIO>(this.detach_COMENTARIOs1));
			this._EXP_EDUCACIONALEs = new EntitySet<EXP_EDUCACIONALE>(new Action<EXP_EDUCACIONALE>(this.attach_EXP_EDUCACIONALEs), new Action<EXP_EDUCACIONALE>(this.detach_EXP_EDUCACIONALEs));
			this._EXP_EMPRENDEDOREs = new EntitySet<EXP_EMPRENDEDORE>(new Action<EXP_EMPRENDEDORE>(this.attach_EXP_EMPRENDEDOREs), new Action<EXP_EMPRENDEDORE>(this.detach_EXP_EMPRENDEDOREs));
			this._EXP_LABORALE = default(EntityRef<EXP_LABORALE>);
			this._PROFESIONE = default(EntityRef<PROFESIONE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_PATERNO", DbType="VarChar(100)")]
		public string APELLIDO_PATERNO
		{
			get
			{
				return this._APELLIDO_PATERNO;
			}
			set
			{
				if ((this._APELLIDO_PATERNO != value))
				{
					this.OnAPELLIDO_PATERNOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO_PATERNO = value;
					this.SendPropertyChanged("APELLIDO_PATERNO");
					this.OnAPELLIDO_PATERNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_MATERNO", DbType="VarChar(100)")]
		public string APELLIDO_MATERNO
		{
			get
			{
				return this._APELLIDO_MATERNO;
			}
			set
			{
				if ((this._APELLIDO_MATERNO != value))
				{
					this.OnAPELLIDO_MATERNOChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO_MATERNO = value;
					this.SendPropertyChanged("APELLIDO_MATERNO");
					this.OnAPELLIDO_MATERNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="VarChar(50)")]
		public string FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this.OnFECHA_NACIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_NACIMIENTO = value;
					this.SendPropertyChanged("FECHA_NACIMIENTO");
					this.OnFECHA_NACIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO_PERSONAL", DbType="VarChar(100)")]
		public string TELEFONO_PERSONAL
		{
			get
			{
				return this._TELEFONO_PERSONAL;
			}
			set
			{
				if ((this._TELEFONO_PERSONAL != value))
				{
					this.OnTELEFONO_PERSONALChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO_PERSONAL = value;
					this.SendPropertyChanged("TELEFONO_PERSONAL");
					this.OnTELEFONO_PERSONALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO_CELULAR", DbType="VarChar(100)")]
		public string TELEFONO_CELULAR
		{
			get
			{
				return this._TELEFONO_CELULAR;
			}
			set
			{
				if ((this._TELEFONO_CELULAR != value))
				{
					this.OnTELEFONO_CELULARChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO_CELULAR = value;
					this.SendPropertyChanged("TELEFONO_CELULAR");
					this.OnTELEFONO_CELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUARIO", Storage="_USUARIO1", DbType="VarChar(100)")]
		public string USUARIO1
		{
			get
			{
				return this._USUARIO1;
			}
			set
			{
				if ((this._USUARIO1 != value))
				{
					this.OnUSUARIO1Changing(value);
					this.SendPropertyChanging();
					this._USUARIO1 = value;
					this.SendPropertyChanged("USUARIO1");
					this.OnUSUARIO1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="VarChar(100)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PROFESION", DbType="Int")]
		public System.Nullable<int> ID_PROFESION
		{
			get
			{
				return this._ID_PROFESION;
			}
			set
			{
				if ((this._ID_PROFESION != value))
				{
					if (this._PROFESIONE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PROFESIONChanging(value);
					this.SendPropertyChanging();
					this._ID_PROFESION = value;
					this.SendPropertyChanged("ID_PROFESION");
					this.OnID_PROFESIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_COMENTARIO", Storage="_COMENTARIOs", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO_EMISOR")]
		public EntitySet<COMENTARIO> COMENTARIOs
		{
			get
			{
				return this._COMENTARIOs;
			}
			set
			{
				this._COMENTARIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_COMENTARIO1", Storage="_COMENTARIOs1", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO_RECEPTOR")]
		public EntitySet<COMENTARIO> COMENTARIOs1
		{
			get
			{
				return this._COMENTARIOs1;
			}
			set
			{
				this._COMENTARIOs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_EXP_EDUCACIONALE", Storage="_EXP_EDUCACIONALEs", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO")]
		public EntitySet<EXP_EDUCACIONALE> EXP_EDUCACIONALEs
		{
			get
			{
				return this._EXP_EDUCACIONALEs;
			}
			set
			{
				this._EXP_EDUCACIONALEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_EXP_EMPRENDEDORE", Storage="_EXP_EMPRENDEDOREs", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO")]
		public EntitySet<EXP_EMPRENDEDORE> EXP_EMPRENDEDOREs
		{
			get
			{
				return this._EXP_EMPRENDEDOREs;
			}
			set
			{
				this._EXP_EMPRENDEDOREs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_EXP_LABORALE", Storage="_EXP_LABORALE", ThisKey="ID_USUARIO", OtherKey="ID_EXP_LABORAL", IsUnique=true, IsForeignKey=false)]
		public EXP_LABORALE EXP_LABORALE
		{
			get
			{
				return this._EXP_LABORALE.Entity;
			}
			set
			{
				EXP_LABORALE previousValue = this._EXP_LABORALE.Entity;
				if (((previousValue != value) 
							|| (this._EXP_LABORALE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EXP_LABORALE.Entity = null;
						previousValue.USUARIO = null;
					}
					this._EXP_LABORALE.Entity = value;
					if ((value != null))
					{
						value.USUARIO = this;
					}
					this.SendPropertyChanged("EXP_LABORALE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESIONE_USUARIO", Storage="_PROFESIONE", ThisKey="ID_PROFESION", OtherKey="ID_PROFESION", IsForeignKey=true)]
		public PROFESIONE PROFESIONE
		{
			get
			{
				return this._PROFESIONE.Entity;
			}
			set
			{
				PROFESIONE previousValue = this._PROFESIONE.Entity;
				if (((previousValue != value) 
							|| (this._PROFESIONE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROFESIONE.Entity = null;
						previousValue.USUARIOs.Remove(this);
					}
					this._PROFESIONE.Entity = value;
					if ((value != null))
					{
						value.USUARIOs.Add(this);
						this._ID_PROFESION = value.ID_PROFESION;
					}
					else
					{
						this._ID_PROFESION = default(Nullable<int>);
					}
					this.SendPropertyChanged("PROFESIONE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COMENTARIOs(COMENTARIO entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = this;
		}
		
		private void detach_COMENTARIOs(COMENTARIO entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = null;
		}
		
		private void attach_COMENTARIOs1(COMENTARIO entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO1 = this;
		}
		
		private void detach_COMENTARIOs1(COMENTARIO entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO1 = null;
		}
		
		private void attach_EXP_EDUCACIONALEs(EXP_EDUCACIONALE entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = this;
		}
		
		private void detach_EXP_EDUCACIONALEs(EXP_EDUCACIONALE entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = null;
		}
		
		private void attach_EXP_EMPRENDEDOREs(EXP_EMPRENDEDORE entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = this;
		}
		
		private void detach_EXP_EMPRENDEDOREs(EXP_EMPRENDEDORE entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="innova.MENSAJES")]
	public partial class MENSAJE
	{
		
		private System.Nullable<int> _ID_MENSAJE;
		
		private string _ASUNTO;
		
		private string _MENSAJE1;
		
		private System.Nullable<System.DateTime> _FECHA_ENVIO;
		
		private System.Nullable<int> _ID_EMISOR;
		
		private System.Nullable<int> _ID_RECEPTOR;
		
		public MENSAJE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MENSAJE", DbType="Int")]
		public System.Nullable<int> ID_MENSAJE
		{
			get
			{
				return this._ID_MENSAJE;
			}
			set
			{
				if ((this._ID_MENSAJE != value))
				{
					this._ID_MENSAJE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASUNTO", DbType="VarChar(50)")]
		public string ASUNTO
		{
			get
			{
				return this._ASUNTO;
			}
			set
			{
				if ((this._ASUNTO != value))
				{
					this._ASUNTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="MENSAJE", Storage="_MENSAJE1", DbType="VarChar(MAX)")]
		public string MENSAJE1
		{
			get
			{
				return this._MENSAJE1;
			}
			set
			{
				if ((this._MENSAJE1 != value))
				{
					this._MENSAJE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ENVIO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHA_ENVIO
		{
			get
			{
				return this._FECHA_ENVIO;
			}
			set
			{
				if ((this._FECHA_ENVIO != value))
				{
					this._FECHA_ENVIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EMISOR", DbType="Int")]
		public System.Nullable<int> ID_EMISOR
		{
			get
			{
				return this._ID_EMISOR;
			}
			set
			{
				if ((this._ID_EMISOR != value))
				{
					this._ID_EMISOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_RECEPTOR", DbType="Int")]
		public System.Nullable<int> ID_RECEPTOR
		{
			get
			{
				return this._ID_RECEPTOR;
			}
			set
			{
				if ((this._ID_RECEPTOR != value))
				{
					this._ID_RECEPTOR = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
